# -*- coding: utf-8 -*-
"""じゃんけん

Automatically generated by Colab.

"""

import random, unicodedata
result = {"win":0, "lose":0, "draw":0}

# じゃんけんの手を選ぶ
def choose_hand():
  HANDS = ["グー", "チョキ", "パー"]
  while True:
    hand = input("グー・チョキ・パーのいずれかを入力してください")
    if hand not in HANDS:
      print("入力が不正です。\n もう一度入力してください。")
    else:
      comp = random.choice(HANDS)
      print(f"コンピューターは {comp} を出しました")
      return hand,comp

# じゃんけんをする
def judge(hand,comp):
  if hand == comp:
        result["draw"] += 1
        return "引き分けです"
  elif (hand == "グー" and comp == "チョキ") or \
       (hand == "チョキ" and comp == "パー") or \
       (hand == "パー" and comp == "グー"):
        result["win"] += 1
        return "あなたの勝ちです！"
  else:
        result["lose"] += 1
        return "あなたの負けです"

# 再戦するか尋ねる
def q_rep(count):
  while True:
    repeat = input("もう一度プレイしますか？ y/n: ")
    repeat = unicodedata.normalize("NFKC", repeat).strip().lower()
    if repeat == "n":
      return False
    elif repeat == "y":
      count += 1
      return(count)
    else:
      print("入力が不正です。\n もう一度入力してください。")


# ここから実行内容

roop_count = 1
print(f"◇ {roop_count} 戦目を行います")

while True:
  hand,comp =  choose_hand()
  print(judge(hand,comp))
  print(f"勝ち：{result['win']}回　負け：{result['lose']}回　引き分け：{result['draw']}回")
  roop_count = q_rep(roop_count)
  if roop_count is False:
    print("ゲームを終了します")
    break
  print(f"◇ {roop_count} 戦目を行います")
